const QuestionIndexTypes ={
    SET_LENGTH:'GETSET_LENGTH_LENGTH',
    SET_TYPE_INCREASE_QUESTIONS:'SET_TYPE_INCREASE_QUESTIONS',
    SET_INDEX:'SET_INDEX',
    INCREASE_INDEX:'INCREASE_INDEX',
    DECREASE_INDEX:'DECREASE_INDEX',
    RUNNING_OUT_OF_TIME: 'RUNNING_OUT_OF_TIME',
};

export default QuestionIndexTypes;