const ScoresStudents = {
    SET_STUDENTID:'SET_STUDENTID',
    INCREASE_STUDENT:'INCREASE_STUDENT',
    INCREASE_SCORE:'INCREASE_SCORE',
    DECREASE_SCORE:'DECREASE_SCORE'
}

export default ScoresStudents;