const QuestionCourseTypes = {
    SET_QUESTIONS_COURSENAME:'SET_QUESTIONS_COURSENAME',
    SET_EXAM_PARENT_ID :'SET_EXAM_PARENT_ID',
    SET_QUESTIONS_NAME_OF_COURSE:'SET_QUESTIONS_NAME_OF_COURSE',
};

export default QuestionCourseTypes;