const ResponsesStudentTypes = {
    SET_EXAM_PARENT_ID_FOR_RESPONSR : 'SET_EXAM_PARENT_ID_FOR_RESPONSR',
    SET_RESPONSE_STUDENT:'SET_RESPONSE_STUDENT',
    GET_RESPONSE_STUDENT:'GET_RESPONSE_STUDENT',
    CLEAR_RESPONSE_STUDENT:'CLEAR_RESPONSE_STUDENT',
    CLEAR_RESPONSE_STUDENT_TIMEOUT:'CLEAR_RESPONSE_STUDENT_TIMEOUT',
};

export default ResponsesStudentTypes;