const TimeLoginToPageTypes ={
    TIMETOATTENDTHEEXAMPAGE : 'TIMETOATTENDTHEEXAMPAGE',
    CLEARTIMETOATTENDTHEEXAMPAGE :'CLEARTIMETOATTENDTHEEXAMPAGE' ,
    CLEARTIMETOATTENDTHEEXAMPAGEWITHTIMEOUT:'CLEARTIMETOATTENDTHEEXAMPAGEWITHTIMEOUT',
};

export default TimeLoginToPageTypes;